### PR TITLE
fix: search box max suggestions not working as expected

### PR DESCRIPTION
**Pull request by vrjuliao**
I'm trying changing max suggestions like the link
https://vuepress.vuejs.org/default-theme-config/#search-box
But it was not work.

I fix this bug.

**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [x] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by f3ltron** [comment]
Hello @vrjuliao ! Thank's for the PR Maybe it's more a bug coming into the constant. I will have a look at it soon.

**Comment by kefranabg** [comment]
Hi @vrjuliao,

Thanks for this PR 👍 
Could you remove all the changes that concerns code formatting?
Let's focus on the `maxSuggestion` feature 😉

**Comment by vrjuliao** [comment]
hi @kefranabg, thanks for your suggestion. But, I didn't change the code formatting, I've just changed one line of code.

Now, I trying to resolve the conflicts and I see so many changes.
I guess these changes are contained on another pull request, like the semilcolon: commomnly I dont put it on the end lines in ECS code, however there are another than kind of this change type .

**Comment by kefranabg** [comment]
@vrjuliao Ok ! @f3ltron could you take a look ?

**Comment by f3ltron** [comment]
There is some code formating and it look's good to me for stylus i pref to have {} instead of nothing for readability.

a key not present in for loop. The thing i should not add that the "". But it will be corrected with the linter.

I valid this pr

**Comment by f3ltron** [comment]
thx @vrjuliao for your work 👍

**Pull request merged**
