### PR TITLE
feat: Improved the Native Search Algorithm

### PR DESCRIPTION
**Pull request by ynnelson**
**Summary**

You can now search tags in addition to H2 and H3 titles as well as the search can now take in multiple words separated by a space.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [x] Other, please describe:

I simply improved the `suggestions ()` method in the SearchBox component to now include tags if they exist in the frontmatter, this is combined with the existing behavior of searching through headers. Also, the other improvement is that you can now do a search based on multiple keywords as opposed to only one previously.

This is a very minor adjustment which I think will satisfy a lot of the issues with the native search and allows the user to make pages show up in the search based on the tags assigned to it.

The only change to the UI was to make the suggestion box search sit `0.5 rem` lower on the navbar.

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [x] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by gevera** [comment]
This is very helpful. I hope it will get merged soon

**Comment by Raiondesu** [comment]
+1 for this.

**Comment by ulivz** [comment]
Great work, but could you write full tests for it?

**Comment by ynnelson** [comment]
Pardon my ignorance but I am not really sure how to write full tests for this... could you point me to another test in the repo, that would be helpful in seeing what I need to write up. Thank you. @ulivz

**Comment by ynnelson** [comment]
If someone could point me to an example on how to write a test for this, I'd happily do it! @ulivz

**Comment by f3ltron** [comment]
It has been a while since you create the pr ! 

I will have a look about create tests needed @ynnelson  thank's for your work

**Comment by gevera** [comment]
Any progress on this feature?

**Comment by kyle-tightest** [comment]
Can someone merge please?

**Comment by ynnelson** [comment]
I resolved the conflict, not sure about how to solve the 1 check that failed.

**Comment by kyle-tightest** [comment]
@ynnelson there seems to be some linting issues on `SearchBox.vue`: https://circleci.com/gh/vuejs/vuepress/2803?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

The other check for "Semantic Pull Request" seems to be due to the title.  
I think prefixing the pull request with `feat: ` would solve that.

**Comment by kyle-tightest** [comment]
@ynnelson you could also give me write access to your branch and I'll make the required changes.

**Comment by ynnelson** [comment]
@kyle-tightest I added you as a collaborator.

**Comment by kyle-tightest** [comment]
@ynnelson thanks. Can you please change this pull request's title to `feat: Improved the Native Search Algorithm`? I dont have access to change the title.

**Comment by ynnelson** [comment]
This is ready to be merged i think.

**Comment by kyle-tightest** [comment]
@f3ltron

**Comment by Royedc4** [comment]
Hey guys this is very relevant, when will this be merged? Cheers!

**Comment by f3ltron** [comment]
i am gonna ask to them if they can't put it for the next release

**Comment by sarahdayan** [comment]
Hey @ynnelson! As @ulivz said I still think there would be value in testing this. This way, we can fully validate the behavior on our end, and improve the algorithm later on without breaking expectations.

If you extract the logic outside of the component, this should be easy to test. I'm available to help you if you need.

**Comment by kefranabg** [comment]
I just added some tests. One more review and it will be ready to be merged 🎉

**Pull request merged**
