### PR TITLE
fix:  #1845 bump js-yaml

### PR DESCRIPTION
**Pull request by yjkimjunior**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)
It's pretty trivial and the tests pass.
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by f3ltron** [comment]
Hello ! Thx for PR is there any reason to update to this version ?

**Comment by yjkimjunior** [comment]
@f3ltron thanks for the quick response! I raised the issue here. https://github.com/vuejs/vuepress/issues/1845

**Comment by yjkimjunior** [comment]
basically: 

`nodeca/js-yaml#475`
Versions js-yaml prior to 3.13.0 are vulnerable to Denial of Service. By parsing a carefully-crafted YAML file, the node process stalls and may exhaust system resources leading to a Denial of Service.

`nodeca/js-yaml#480`
Js-yaml prior to 3.13.1 are vulnerable to Code Injection. The load() function may execute arbitrary code injected through a malicious YAML file.

**Comment by kefranabg** [comment]
Hi @yjkimjunior,

I don't see any changes on `yarn.lock`?

**Comment by kefranabg** [comment]
@yjkimjunior How did you update the `yarn.lock`? It seems that there is a lot of changes for just one dependency update 🤔

**Comment by yjkimjunior** [comment]
I just bumped the version number there, then `rm yarn.lock && yarn`

**Comment by kefranabg** [comment]
Ok, that's what I thought 😉 Doing this is kind of risky. However I made a test by running `yarn upgrade js-yaml@latest` and it just changed package.json (not yarn.lock) so you can revert your last commit. Sorry for that @yjkimjunior

**Pull request merged**
