### PR TITLE
VuePress Next Alpha

### LINKED ISSUE #729: Define custom component directory and import custom components
## Feature request

Allow developers to use the `config.js` file to customize the components folder and to import components with custom names.

#### What problem does this feature solve?
Currently, VuePress looks for a `components` folder inside the `.vuepress` folder. If we are aiming to integrate VuePress into an existing project (or use it to document a custom component package), this would drive us to move or copy existing components to this folder. This results in either verbosity (as we would have to import from `./path/to/.vuepress/components`) or duplication.

Moreover, the current implementation does not allow us to import custom components with a custom name tag, relying solely on the folder structure of the component (e.g. `<Path-To-Custom-Component></Path-To-Custom-Component>`.

#### What does the proposed API look like?

- Custom component directory:

carbon 25

- Custom component import:

carbon 24

#### How should this be implemented in your opinion?
First, modifying the `resolveOptions.js` to accept two new options (`components` and `componentsDir`). Then, modifying the `genImport` function in the `codegen.js ` to accept these options and generate the imports based on their values.

#### Are you willing to work on this yourself?**
Yes. [#730](https://github.com/vuejs/vuepress/pull/730)

### PR DESCRIPTION
**Pull request by ulivz**
## `Status`: ≈ 96% ready and feedbacks are welcome. 

---

### Plugin API

- [Documentation (WIP)](https://github.com/vuejs/vuepress/tree/next/packages/docs/docs/plugin)
- Multiple official plugins
  - [@vuepress/plugin-active-header-links](https://github.com/vuejs/vuepress/tree/next/packages/@vuepress/plugin-active-header-links)
  - [@vuepress/plugin-back-to-top](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-back-to-top) (Thanks to @ycmjason )
  - [@vuepress/plugin-blog](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-blog) (For blog theme developers.)
  - [@vuepress/plugin-pagination](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-pagination) (For blog theme developers.)
  - [@vuepress/plugin-google-analytics](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-google-analytics)
  - [@vuepress/plugin-last-updated](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-last-updated) 
  - [@vuepress/plugin-i18n-ui](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-i18n-ui)
  - [@vuepress/plugin-medium-zoom](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-medium-zoom) 
  - [@vuepress/plugin-pwa](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-pwa)
  - [@vuepress/plugin-register-components](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-register-components) 

### Refined Theme API

- [Documentation (WIP)](https://github.com/vuejs/vuepress/tree/next/packages/docs/docs/theme)

### Markdown file slots

- Define slots:
  
```html
- Evan You

<template slot="projects">

    - Vue.js
    - VueX

</template>
```

- Using slots:

```vue
<Content/> <!-- get default slot -->
<Content slot="projects"> <!-- get named slot -->
```

### Free to add new pages

You can add new pages with content (i.e. pointing to markdown files) or no content (i.e. common routes). 

### Custom temp path

```bash
vuepress dev docs --temp .temp
```
 
### Clean layout

In the past, custom layouts were actually implemented by `default theme`, now it's moved to `core`.

## Major internal Changes

1. Leverage monorepo;
2. Decouple [@vuepress/core](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/core) and [@vuepress/theme-default](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/theme-default)
3. Rewrite `Prepare` with `Plugin API`

## TODO

1. Improve ducumentation;
2. Prepare an online slide or article to introduce VuePress Next;
3. Official blog theme;
4. Clean URL (#603);
5. Hoist search as a plugin;
6. Introduce `markdown-it-chain` to make markdown configurable; (Low priority);
7. Rest feature requests.

## Release plan 

**alpha** (Sep. - Oct.) => **beta** (Nov.) => **rc** (Dec. - Jan.)

## Close

Close: #160 (Dynamic routes do not get generated with build)
Close: #281 (Register global components in themes )
Close: #372 (back to top button)
Close: #434 (light-box)
Close: #452 (Data files and dynamic page generation support)
Close: #465 (Page Level Encryption)
Close: #549 (Ability to read/compile .MD file from installed npm module)
Close: #573 (light-box)
Close: #576 (Choosing 404.vue)
Close: #594 (Last Update should be support to change date format pattern)
Close: #600 (custom themeLayoutPath)
Close: #662 (Open config to custom themes)
Close: #723 (Change temp directory)
Close: #729 (Define custom component directory and import custom components)
Close: #733 (Config the dev and build html template. )
Close: #758 (Add webpackServer config)
Close: #771 ([cli] Expose clean build)
Close: #786 (`vuepress build` command will effect other `vuepress dev` command in running. )
Close: #790 (How can I add pure js code to `index.html`)

---

cc @yyx990803

### CODE REVIEW

**Comment by meteorlxy** [comment]
:tada:

**Comment by visamz** [comment]
👍So Cool.

**Comment by yyx990803** [comment]
Nice work!

**Comment by CommanderXL** [comment]
cool👍

**Comment by visamz** [comment]
Looking forward to deploying it ....

**Comment by ulivz** [comment]
I create a blog showcase which is the first website built by VuePress Next: http://www.v2js.com/vuepress-theme-egoist.

**Comment by yyx990803** [comment]
@ulivz I almost thought it was @egoist 's real blog 😂

**Comment by ekoeryanto** [comment]
can't wait the release 😍

**Comment by ekoeryanto** [comment]
any plan to introduce build hook that emit rendered html string?

**Comment by ulivz** [comment]
@willin Hmmm... We don't release yet. cannot you see it: https://github.com/vuejs/vuepress/issues/36#issuecomment-422619094 ???

**Comment by ekoeryanto** [comment]
I am ready with my 🎆 fireworks

**Comment by Oscarteg** [comment]
All the plugin links are giving a 404.

**Pull request merged**
