### PR TITLE
fix($theme-default): fix xml link issue (fix #2292)

### LINKED ISSUE #2292: unexpected nav link
- [x] I confirm that this is an issue rather than a question.

## Bug report

Found on [stackoverflow](https://stackoverflow.com/questions/61076265/unexpected-rss-link)

#### Steps to reproduce

```js
// .vuepress/config.js
module.exports = {
  themeConfig: {
    nav: [
      { text: 'RSS', link: '/rss.xml' }
    ]
  }
}
```

#### What is expected?

get link in nav `/rss.xml`

#### What is actually happening?

got `/rss.xml.html`

#### Other relevant information

### PR DESCRIPTION
**Pull request by Mister-Hope**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge
- [ ] IE

### CODE REVIEW

**Comment by newsbielt703** [comment]
Not only xml file. People might use JSON feed or ATOM feed or something else. I'd like to track it down why `.html` suffix is necessary.

**Comment by Mister-Hope** [comment]
> Not only xml file. People might use JSON feed or ATOM feed or something else. I'd like to track it down why `.html` suffix is necessary.

Since I have rewrote theme-default in ts in my theme, so I can tell you the suffix is not necessary, you can write in a different style, just changing the md suffix to html. It works totally fine. But in my thought, uliz means to restrict the link to only valid web page links, not any links the user provided.

**Comment by Mister-Hope** [comment]
If you need, I can force push this PR to allow any links the user provides, and changed md suffix to html. It's quite simple.

**Comment by Mister-Hope** [comment]
If you need, I can force push this PR to allow any links the user provides, and changed md suffix to html. It's quite simple.

**Comment by Mister-Hope** [comment]
I have open a new PR #2313, so I will close this one. Check that out when you have time @newsbielt703

**Pull request closed without merging**
