### PR TITLE
feat($core): Upgrade vue version

### PR DESCRIPTION
**Pull request by kefranabg**
**Summary**

There is already a [PR](https://github.com/vuejs/vuepress/pull/1370/files) to upgrade vue version in vuepress, but is now outdated. I created a new one with the latest versions.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [x] Other, please describe: Upgrade deps

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by f3ltron** [comment]
Markdown slot @kefranabg is in some md you write <component #header /> if I remember well

**Comment by f3ltron** [comment]
As you create a new one i close this one https://github.com/vuejs/vuepress/pull/1370

**Comment by kefranabg** [comment]
Markdown slots still working ! 🎉

**Comment by ulivz** [comment]
Unfortunately there is a conflict that should be addressed.

**Comment by kefranabg** [comment]
Resolved!

**Pull request merged**
