### PR TITLE
Correction of bug in component

### PR DESCRIPTION
**Pull request by luisDanielRoviraContreras**
Correction of bug in component without having the key property

### CODE REVIEW

**Comment by ulivz** [comment]
although I knew this context, but a good **bug fix PR** is better to provide the context (How to repro), so that it's friendly to future review.

**Comment by ulivz** [comment]
So I just can guess your config, I repro this bug with following config:

```js
       nav: [
          {
            text: 'Guide',
            link: '/guide/',
          },
          {
            text: 'Config Reference',
            link: '/config/'
          },
          {
            text: 'test',
            items: [
              {
                text: 'Guide',
                link: '/guide/',
              },
              {
                text: 'Config Reference',
                link: '',
                items: [
                  {
                    text: 'Guide',
                    link: '/guide/',
                  },
                  {
                    text: 'Config Reference',
                    link: '/config/'
                  }
                ]
              },
              {
                text: 'Config Reference',
                link: '',
                items: [
                  {
                    text: 'Guide',
                    link: '/guide/',
                  },
                  {
                    text: 'Config Reference',
                    link: '/config/'
                  }
                ]
              }
            ]
          },
          {
            text: 'Default Theme Config',
            link: '/default-theme-config/'
          }
        ],
```

In fact, you can just remove the empty link (`link: ''`) to fix it, but this PR is valuable.

**Comment by luisDanielRoviraContreras** [comment]
To reproduce the error you have to put in `.vuepress / config.js` the empty links inside` nav` in this case

**Comment by ulivz** [comment]
Will release it at 0.9.0: #419. 🚀

**Pull request merged**
