### PR TITLE
Docs: fix a command bug

### PR DESCRIPTION
**Pull request by ChungZH**
**Summary**
Fix a command bug in Chinese doc.

**Before**: `yarn build:docs` & `npm run build:docs`

**After**: `yarn docs:build` & `npm run docs:build`

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by newsbielt703** [comment]
It totally depends on what the property name you set to your NPM scripts

**Comment by newsbielt703** [comment]
Oh, I get it. The example commands isn't sync between zh and en docs. That't your point, right?

**Comment by ChungZH** [comment]
Haha, that's it :smile:
Actually, this is not only **isn't sync**, this command is wrong

**Comment by meteorlxy** [comment]
Sorry didn't notice this PR. Has already fixed in #2284

**Pull request closed without merging**
