### PR TITLE
feat($theme-default): add initial open group index option

### PR DESCRIPTION
**Pull request by dennisreimann**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [x] Related documents have been updated
- [ ] Related tests have been updated

Adds an optional property for sidebar groups, so that one can initially display a group other than the first as open. Also allows to initially display all groups as closed, by setting `initialOpenGroupIndex` to `-1`.

### CODE REVIEW

**Comment by dennisreimann** [comment]
Is this a change that's wanted? If so, what can I provide to get it towards integration?

**Comment by dennisreimann** [comment]
@ulivz Of course. I've added a bit more info and rebased the branch. Let me know if there is more to do.

**Comment by dennisreimann** [comment]
@ulivz ok like this?

**Comment by dennisreimann** [comment]
Don‘t want to be pushy with this, but we could use this and I don‘t want it to drown. Let me know if further improvements are needed.

**Comment by dennisreimann** [comment]
@bencodezen @billyyyyy3320 @kefranabg any chance to get this merged?

**Comment by dennisreimann** [comment]
Awesome, thanks for merging 🚀

**Comment by Thief-K** [comment]
When i am looking for some solution to change the open index from the source code, and it just commited yesterday! What a coincidence!

**Comment by Thief-K** [comment]
How about using global config such as "themeConfig.defaultOpen" to control the collapse status of sidebar items, because the "initialOpenGroupIndex" does not work in "Sidebar.vue" file

**Pull request merged**
