### PR TITLE
feat: allow no v-pre on code blocks (#413)

### LINKED ISSUE #413: [Feature Request] Interpolation Expression in code block (Allow no v-pre at code block)
I'm using vue press 0.8.4 for technical docs and generally works great, thanks a lot for the great project!

However, we'd like to use variable expansion in markdown code. Example, a code block like

<pre><code>
```
cd ~/projects/{{ $project }}/vcs/
```
</pre></code>

would show `cd ~/projects/{{ $project }}/vcs/` although the variable $project is registered. It works correctly when markdown code formatting is not used. 
Is there a way to make variable expansion / vue processing of markdown processed html work?

This feature would allow the technical docs to use replacement patterns where meaningful, so any changes to those docs can be done easily by changing the variables.

### PR DESCRIPTION
**Pull request by meteorlxy**
close #413

### CODE REVIEW

**Comment by meteorlxy** [comment]
@ulivz Modified. Further review wanted 😄 .

**Comment by rasapetter** [comment]
Any updates this? Would love to be able to use this feature to get a centrally configurable domain name injected into many code blocks spread out over a semi-large documentation project.

**Comment by meteorlxy** [comment]
@rasapetter 

So many changes after the last commit of the PR.

This feature is still to be determined. Maybe it will be finished in the next version. It's up to the maintainer. 😄

**Comment by ulivz** [comment]
Closing since for now it can be addressed by a plugin.

**Pull request closed without merging**
