### PR TITLE
fix($plugin-pagination): get posts calculation error

### PR DESCRIPTION
**Pull request by lhz960904**
**Summary**
This plugin enhanceAppFile  calculation errors to  get posts.  When Max is 20 interval 10, it will slice [0, 11], [10, 21] ，but the right result should be [0, 10] [10, 20]

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by f3ltron** [comment]
I will have a look of this pr. Maybe is more about the end calculation @lhz960904  ?

**Comment by f3ltron** [comment]
@lhz960904 can you provide me a repo example please to validate a push the merge conflict resolve

**Comment by f3ltron** [comment]
#1345 relation with that pr too

**Comment by lhz960904** [comment]
> @lhz960904 can you provide me a repo example please to validate a push the merge conflict resolve
emm,  this pr  happened long long ago， at that time , there is not merge conflict .  so now I don't know how to resolve .  sorry

**Comment by f3ltron** [comment]
just git pull origin master and resolve from here

**Comment by ulivz** [comment]
This pagination plugin has been deprecated and merged into blog plugin, you can move this pull request to [here](https://github.com/ulivz/vuepress-plugin-blog).

**Pull request closed without merging**
