### PR TITLE
style: change dropdown item heading padding (fix #2481)

### LINKED ISSUE #2481: Increase the dropdown item heading padding
#### What problem does this feature solve?

Increase the dropdown item heading padding to improve the user experience of the dropdown menu.

#### What does the proposed change look like?

| Before | After |
|-------------|-------------|
| image | image |

#### How should this be implemented in your opinion?

```diff
diff --git a/packages/@vuepress/theme-default/components/DropdownLink.vue b/packages/@vuepress/theme-default/components/DropdownLink.vue
index 0ca7137e..9cddef3b 100644
--- a/packages/@vuepress/theme-default/components/DropdownLink.vue
+++ b/packages/@vuepress/theme-default/components/DropdownLink.vue
@@ -137,7 +137,7 @@ export default {
       h4
         margin 0.45rem 0 0
         border-top 1px solid #eee
-        padding 0.45rem 1.5rem 0 1.25rem
+        padding 1rem 1.5rem 0.45rem 1.25rem
       .dropdown-subitem-wrapper
         padding 0
         list-style none
```

#### Are you willing to work on this yourself?

Why not? 🏀

### PR DESCRIPTION
**Pull request by gtsiolis**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [X] Other, please describe: Style

If changing the UI of default theme, please provide the **before/after** screenshot:

| Before | After |
|-------------|-------------|
| image | image |

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

Fix #2481

### CODE REVIEW

**Comment by bencodezen** [comment]
Looks great. Thanks so much for this @gtsiolis!

**Comment by gtsiolis** [comment]
Thanks @bencodezen! 🏀

**Comment by billyyyyy3320** [comment]
As convention, `style` is using on "Code style update" (white-space, formatting, missing semi-colons, etc).

**Comment by gtsiolis** [comment]
You're right @billyyyyy3320! Probably copied that from the pull request description. 😭

**Pull request merged**
