### PR TITLE
feat($theme-default): inform screen readers link opens in new tab/window (fix #2601)

### LINKED ISSUE #2601: Inform screen reader users if a link will open in a new tab
#### What problem does this feature solve?
Inform screen reader users in advance if the link will **open in a new tab**.

https://www.w3.org/WAI/WCAG21/Techniques/general/G201
https://webaim.org/techniques/hypertext/hypertext_links#new_window

#### How should this be implemented in your opinion?
Text customized by locales: `$themeLocaleConfig.openNewWindowText`

#### Are you willing to work on this yourself?
Yes

### PR DESCRIPTION
**Pull request by d-pollard**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by d-pollard** [comment]
@ktquez - thanks for the review; added changes accordingly!

**Review by bencodezen — APPROVED** [review]
Great enhancement @d-pollard!

**Comment by khs1994** [comment]
how to disable it?

**Comment by ktquez** [comment]
@khs1994 Why?

Nothing changes visually. 
I don't think it should be disabled.

But if you still want to modify this, you can replace the `convert-router-link` plugin.

**Comment by khs1994** [comment]
my nav show `(opens new window)`,how to hide it?

**Comment by ktquez** [comment]
@khs1994 
https://github.com/vuejs/vuepress/pull/2650#issuecomment-708238538

**Pull request merged**
