### PR TITLE
fix(hmr): upgrade http-proxy

### LINKED ISSUE #2392: Hot reload not working
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

```
$ yarn add vuepress --dev
$ mkdir docs
$ youch docs/index.md
$ yarn vuepress dev docs

success [08:52:12] Build 1d01b9 finished in 172 ms! ( http://localhost:8080/ )
```

#### What is expected?

Vuepress CLI detects file changes and rebuilds.

#### What is actually happening?

Vuepress CLI doesn't detect file changes. I have to run `vuepress dev docs` again to build codes.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
% npx vuepress info

Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 14.2.0 - ~/.nodebrew/current/bin/node
    Yarn: 1.22.4 - ~/.nodebrew/current/bin/yarn
    npm: 6.14.4 - ~/.nodebrew/current/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: Not Found
    Safari: Not Found
  npmPackages:
    @vuepress/core:  1.5.0 
    @vuepress/theme-default:  1.5.0 
    vuepress: ^1.5.0 => 1.5.0 
  npmGlobalPackages:
    vuepress: Not Found
```

### PR DESCRIPTION
**Pull request by posva**
Fix #2392
Upgrades http-proxy

**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by newsbielt703** [comment]
Could you tell me how to reproduce it? I can't reproduce the issue to test this PR.

**Comment by posva** [comment]
Sure, in a fresh project:

```sh
mkdir bug-vuepress
cd bug-vuepress
yarn init -y
yarn add vuepress --dev
mkdir docs
touch docs/README.md
yarn vuepress dev docs
```

Open the docs in the browser, change anything in the page and you will see it doesn't update.

I tried locally by building vuepress with this change and linking it and it fixed the problem. That being said, I didn't find a reason in http-proxy's changelog that would help understanding what broke it in the first place...

**Comment by sodatea** [comment]
I don't think it fixed that problem.

**Comment by sodatea** [comment]
1. Upgrading `yarn.lock` in the project does not fix a bug in the userland.
2. As described, a *linked* vuepress dependency fixed the problem. It's because the lockfile in this project hasn't been updated in months, it does not have the newly-introduced broken dependency anyway.

---

The root problem is chokidar - I'm still trying to understand why chokidar v3 in watchpack breaks the functionality, but the problem lies there.

**Comment by newsbielt703** [comment]
> 1. Upgrading `yarn.lock` in the project does not fix a bug in the userland.
> 2. As described, a _linked_ vuepress dependency fixed the problem. It's because the lockfile in this project hasn't been updated in months, it does not have the newly-introduced broken dependency anyway.
> 
> The root problem is chokidar - I'm still trying to understand why chokidar v3 in watchpack breaks the functionality, but the problem lies there.

Thanks for the details.

**Comment by sodatea** [comment]
The bug is that `chokidar` used by vuepress and webpack resolves to different instances.

https://github.com/vuejs/vuepress/blob/c6a3cb59275b095bc69e392d77a982a6334f6551/packages/%40vuepress/core/lib/node/dev/index.js#L67-L79

I'd like to explain in detail but it's too late here, I need to go to bed now. So here's the short version:

The implementation in vuepress was never correct. It didn't listen to `change` events. It's just that when webpack and vuepress use the same chokidar instance, the listener in webpack also reacts to the source files' `change` events, so hot reload happens to work.

(Or, maybe it's intentional to reuse the same `chokidar` instance? But such usage is not reliable anyway. It should be fixed)

**Comment by ulivz** [comment]
@sodatea 

> The implementation in vuepress was never correct, It didn't listen to change events.

No, since all the `*.md` will be processed as a dynamic component, e.g.

```js
export default {
  "v-0c799b30": () => import("/.../@vuepress/core/lib/node/docs.fallback/README.md") 
}
```

all the md files will be included in the webpack compilation flow by default, we don't need watch it.

---

Tthis issue is actually introduced by this [commit](https://github.com/micromatch/anymatch/commit/02257b97c7fe760a7fd8cd0f737df66fc37d94e3#diff-168726dbe96b3ce427e7fedce31bb0bc) from `anymatch`, with the refactoring of implementation, we'll get following changes:

- Before:

```
chokidar.watch.target: '/a'
chokidar.ignore: ['!/b'],
is target included: true
```

- After:

```
chokidar.watch.target: '/a'
chokidar.ignore: ['!/b'],
is target included: false
```

---

Closed as it was fixed by #2436.

**Pull request closed without merging**
