### PR TITLE
[WIP] feat: markdown.extractHeaders option

### LINKED ISSUE #1903: Cannot access page headers that are not h2 or h3
- [x] I confirm that this is an issue rather than a question.

## Bug report
Currently, header levels are hard-coded in [VuePress core](https://github.com/vuejs/vuepress/blob/543fd6c8534cd13af5aa97d050748dd916f67ce9/packages/%40vuepress/core/lib/node/Page.js#L117). 

This limits our ability to access header levels beyond `h3`.

Our use case for this is a custom table of contents component that we are displaying on every page of our site. Our content uses `h4`s. 

We don't want header levels below `h3` to show up in our table of contents; however, we'd like for the preceding `h3` to maintain the active indicator once a user has scrolled past an `h4`.

#### What is expected?
There should be some way to customize the header levels that are stored in `this.$page.headers`.

#### What is actually happening?
Header levels stored in `this.$page.headers` are hard-coded to only include `h2` and `h3`.

cc @shortdiv

### PR DESCRIPTION
**Pull request by ulivz**
**Summary**

Fix #1903

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

```js
module.exports = {
  markdown: {
    extractHeaders: ['h2', 'h3', 'h4'] // defaults to ['h2', 'h3'] 
  }
}
```

Replacement of #1111

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

**This is my 1st work with [Gitpod](https://www.gitpod.io/)**

### CODE REVIEW

**Comment by funnycoderstar** [comment]
This is exactly what I want.

**Comment by ulivz** [comment]
Issue of this pull request is that sidebar of VuePress doesn't support infinite nesting. even we extract more headers, extra headers will not be indented.

Maybe we need to fix the indent problem before getting this pull request merged.

// cc @kefranabg @f3ltron

**Comment by kefranabg** [comment]
Seems like I do not have rights to push on this PR 🤔 @funnycoderstar could you enable authors commits on your PR ?

**Comment by kefranabg** [comment]
Close this PR in favor of #1945 as I'm not able to update this one.

**Pull request closed without merging**
