### PR TITLE
✨ Remove '.html' extension from URLs

### PR DESCRIPTION
**Pull request by dcastil**
**Summary**

As discussed in #608 and a few other issues, it would be nice to enhance user experience regarding URLs created by vuepress. I want to make a first step towards this goal with this PR and removed the `.html` extension at the end of all URLs. So the URL `/about.html` gets `/about/`.

However, there is some more work to be done.

1. When I start a project with `vuepress dev` and request a URL without the trailing `/`, the router gets into an infinite loop and a blank website is shown.

2. Generally the trailing `/` should be removed from all URLs. Removing the `.html` extension is only the first step and I wouldn't ship this to production as is.

3. Some refactoring might be needed as a lot of code was built with the URL extension in mind.

I'm open for suggestions and help.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [X] A convincing reason for adding this feature
  → [This comment from awulkan](https://github.com/vuejs/vuepress/issues/608#issue-334865699) has some convincing reasons.
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

I'm not sure if I have enough time to go though all the points mentioned in the summary. If anyone wants to pick up from my work, feel free to fork from my repo and continue working on that.

### CODE REVIEW

**Comment by dcastil** [comment]
@ulivz I created a possible solution. But it makes a lot of functions dependent on the `htmlSuffix` which I don't like, there might be a better solution. I also don't understand why I need to add `.replace(endingSlashRE, '')` to the `normalize` function. If I don't do it, the router errors and the sidebar breaks.

**Comment by awulkan** [comment]
Any update on this? It's the main blocker for me if I'm ever going to consider VuePress. I know a lot of people want it, and have tried to solve it (me included), but I think we need help from the main developers of VuePress to do it.

**Comment by dcastil** [comment]
Unfortunately I don't have time to work on this currently. I'm closing the PR as it is out of date and has too many conflicts.

**Comment by awulkan** [comment]
Understandable. Thanks for the effort.
I'll check back on VuePress in a few months again, maybe someone in the core team has seen the benefits of it by then.

**Comment by Shigma** [comment]
See #1339

**Pull request closed without merging**
