### PR TITLE
 fix($theme-default): add text ellipsis to navbar (#1683)

### PR DESCRIPTION
**Pull request by maoyuyang**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by maoyuyang** [comment]
I don't know why `yarn.lock` changed. I just run` yarn bootstrap ` as `README.md` said ...

**Comment by sarahdayan** [comment]
@maoyuyang Can you rebase your branch onto `master`? This should solve the `yarn.lock` issue.

**Comment by maoyuyang** [comment]
done

**Comment by f3ltron** [comment]
I think there is a lot of commits that should not be there ^^. Can you clean them please

**Comment by maoyuyang** [comment]
sorry... I am still learning git, these redundant commit messages make me confused, I tried some methods, but none of them worked, so I think I should close this PR and open a new one. I'm sorry to trouble you.. orz

**Comment by f3ltron** [comment]
No problem we all started with something 👍

**Pull request closed without merging**
