### PR TITLE
build($theme-default): bump stylus version

### LINKED ISSUE #2227: Overlap on a Navbar Dropdown
- [x] I confirm that this is an issue rather than a question.

## Bug report

When one clicks on several options in the navbar, their drop-down menu options overlap.

#### Steps to reproduce

IMG
Screenshot 2020-03-17 at 12 12 23 PM

If you are reporting a bug that can ONLY be reproduced on your repository, PLEASE provide this repo link. That takes guessing work out of the way and saves us time. 

This can be reproduced on any vuepress site with navbar items included.

#### What is expected?
I should be able to configure the navbar in such a way that this overlap is avoided. It sometimes takes a few secs to get out of this situation when it occurs. Also helpful if there's a way to disable focus on the parent navbar item.

#### What is actually happening?
When I click on several navbar items with dropdown I get this behavior where all dropdown overlaps.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
```bash
Environment Info:

  System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 13.9.0 - ~/.nvm/versions/node/v13.9.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.9.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 73.0.1
    Safari: 12.1.1
  npmPackages:
    @vuepress/core:  1.2.0
    @vuepress/theme-default:  1.2.0
    vuepress: ^1.2.0 => 1.2.0
  npmGlobalPackages:
    vuepress: Not Found
```

### PR DESCRIPTION
**Pull request by JoeyBling**
Use new version to support `@extends` writing

**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

fix #2227

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Review by billyyyyy3320 — COMMENTED** [review]
I don't think such feature will be added in a patch version. Then, I noticed that Stylus has supportted `@extends` since [0.22.0](https://github.com/stylus/stylus/blob/dev/History.md#0220--2012-01-04) by [this commit](https://github.com/stylus/stylus/commit/fa78ec82d2796e22aa474512b4adfaaf2016607d).

**Comment by billyyyyy3320** [comment]
Plus, I cannot reproduce the issue you faced. Could you create another issue with a reproduce approach?

**Comment by JoeyBling** [comment]
@billyyyyy3320 Steps to reproduce：
1. Create a test folder
2. Install the last version of 1.5.3 `npm install vuepress@1.5.3 -S`
3. Install default stylus version 0.54.5 `npm install stylus@0.54.5 -S`
4. Install the latest version of vuepress `npm install vuepress@latest -S`
5. Launch vuepress dev

Console error:
```
Reason: Error: Module build failed (from ./node_modules/stylus-loader/index.js):
Error: C:\Users\24343\Desktop\vuepress-test\node_modules\@vuepress\theme-default\components\DropdownLink.vue:156:15
   152|       vertical-align middle
   153|       margin-top -1px
   154|       margin-left 0.4rem
   155|   .mobile-dropdown-title
   156|     @extends .dropdown-title
----------------------^
   157|     display none
   158|     font-weight 600
   159|     font-size inherit

Failed to @extend ".dropdown-title"
```

**Comment by meteorlxy** [comment]
This should be a "build" commit instead of a "fix" commit.

**Pull request merged**
