### PR TITLE
feat: Using Babel for Vue components inside md files (#318)

### PR DESCRIPTION
**Pull request by HandOfGod94**
Vue components now created with jsx is rendering inside `.md` files.
I have removed `buble-loader` as it will be redundant to use both.
Let me know if we need to check any specific things.

### CODE REVIEW

**Comment by yyx990803** [comment]
Can you confirm async/await works with the setup?

**Comment by HandOfGod94** [comment]
Hi @yyx990803,
Yes, Its working as per the expectation.
I tried with following component.
```javascript
export default {
  name: 'my-component',
  mounted () {
    this.getMsg()
  },
  data () {
    return {
      msg: 'Initial Content'
    }
  },
  methods: {
    getMsg: async function () {
      let promise = new Promise((resolve, reject) => {
        setTimeout(() => resolve("Hello World from async"), 5000)
      })
      let result = await promise;
      this.msg = result
    }
  },
  render (h) {
    return (
      <div>{this.msg}</div>
    )
  }
}
```
And then used it inside `.md` file for demo as
```html
<my-component />
```

**Comment by HandOfGod94** [comment]
Size Comparison

|Application|Before|After|
|---|---|---|
|`VuePress` Docs(Build)| 1.14MB| 1.17MB|
|`CustomApp` Docs(Build)|146KB|168KB|
|`CustomApp with JSX` Docs(Build)|`failed`|168KB|

**Comment by ulivz** [comment]
@HandOfGod94 Thanks for the great work.

**Pull request merged**
