### PR TITLE
workflow: add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ulivz**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by filrak** [comment]
Would be also nice to briefly introduce architecture e.g. explain how plugins/themes interact with core and guide newcomers where they should start to understand how the project works. Nothing too detailed, just brief guidance should be sufficient.

**Comment by sarahdayan** [comment]
I've added PR and commit specs based on the Vue contributing guide. For the rest:

- **Issues**: I think we need to define it together.
- **Substantial changes**: same thing.
- **Code specification**: @ulivz is in the best position to start with this one.

**Comment by f3ltron** [comment]
@filrak  i will on it this week

**Comment by ulivz** [comment]
@f3ltron  Is this pull request ready?

**Comment by f3ltron** [comment]
It is the beginning for me. But as it is yeah @ulivz

**Pull request merged**
