### PR TITLE
feat: add google analytics anonymizeIp in siteConfig

### PR DESCRIPTION
**Pull request by abruere**
**Summary**

A tip about IP anonymization and GDPR was introduced in the docs (https://github.com/vuejs/vuepress/pull/515).

Privacy should be easy: this PR allows to set Google Analytics `anonymizeIp` option without having to write custom theme/code as previously [suggested](https://github.com/vuejs/vuepress/issues/539#issuecomment-409842121).

I would have gladly made this default since it has [little](https://www.conversionworks.co.uk/blog/2018/04/16/ip-anonymization-ga-impact-assessment/) impact on analytics accuracy but this would still be a breaking change and is left to `next` branch (ready to make another PR).

`ga` option can now be a string _or_ an object with `id` and `anonymize` optional boolean attribute defaulting to `false` as explained above.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot: 

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number) > **No issue**

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [x] Related documents have been updated
- [ ] Related tests have been updated > No test for Google Analytics (no debug version)

**Other information:**

I checked that `aip=1` is included in event requests (only) when using the option, as stated by [Google dedicated page](https://support.google.com/analytics/answer/2763052?hl=en).

vuepress anonymizeip aip=

### CODE REVIEW

**Comment by ulivz** [comment]
Thanks for your great work, but could you create this PR to [next](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-google-analytics) 
 branch directly?

**Comment by ekoeryanto** [comment]
I just guess this should be a plugin in the future 1.0

**Comment by abruere** [comment]
Thanks for feedback and for vuepress!

I’ll try to make another PR to [next branch google-analytics plugin](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-google-analytics) you pointed to soon.

I wanted to share this with community as soon as we started using it in production.

V1.0 is not ready yet (https://github.com/vuejs/vuepress/issues/798) and many users will probably stay on ^v0.x.y.

It is a low-effort/high-impact improvement since **it affects all end-users privacy** on vuepress websites with Analytics enabled. *Privacy by default* (starting in v1.0) would be sensible.

I suppose there will be another minor v.0.x.y release at least and according to semver this change could make it to 0.14.3 for instance. I’ve just added the badge for convenience but this is up to you of course.

Note: Failing tests are due to babel version and pass when using https://github.com/vuejs/vuepress/pull/800.

**Comment by ekoeryanto** [comment]
I agree that the v0.x should be accept new feature (PR) as the v1.0 is not yet ready (not even alpha version), as @ulivz said [here](https://github.com/vuejs/vuepress/issues/798#issuecomment-418608183)

**Comment by ulivz** [comment]
We don't plan to maintain two branches at the same time. and `next` is almost ready, so please create this PR for next branch, Thanks!

**Pull request closed without merging**
