### PR TITLE
fix($core): reference correct canonical Url frontmatter property (fix #2665)

### LINKED ISSUE #2665: New `canonicalUrl` frontmatter property is incorrectly mapped in `ClientComputedMixin.js`
- [x] I confirm that this is an issue rather than a question.

#### What is expected?

Canonical Url is grabbed from the `canonicalUrl` entry in the `frontmatter`

#### What is actually happening?

The canonical URL is not being injected into the SSR template because in PR #2658 the frontmatter entry was renamed (during development) **to** `canonicalUrl` **from** `canonical`. 

Line `69` in `packages/@vuepress/core/lib/node/ClientComputedMixin.js` is looking for a non-existent property called `canonical` and needs to be updated to the following:

``` js
const { canonicalUrl } = this.$page.frontmatter
```

Tagging @d-pollard

### PR DESCRIPTION
**Pull request by adamdehaven**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge
- [ ] IE

### CODE REVIEW

**Review by d-pollard — APPROVED** [review]
Good catch! LGTM

**Review by billyyyyy3320 — APPROVED** [review]
LGTM!

**Comment by adamdehaven** [comment]
@d-pollard curious, does this replace the code in the current `1.7.0` or will it be in a future patch? (and if future, when?)

**Comment by d-pollard** [comment]
It'll probably be a different patch, so we'll need to update the docs once the release. Will try to get it in ASAP

**Comment by adamdehaven** [comment]
Ah ok - the docs are correct in the `frontmatter.canonicalUrl` reference. The only thing that would need to be updated is the version number 👍

**Comment by d-pollard** [comment]
@adamdehaven - this should be out now with version 1.7.1

**Comment by d-pollard** [comment]
docs updated too 👍

**Pull request merged**
