### PR TITLE
Feature/search options

### PR DESCRIPTION
**Pull request by chris-visser**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [x] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by sarahdayan** [comment]
Hey @chris-visser, thanks a lot for this PR! Here are a few comments before going into the review:

- Currently, the search options within the `themeConfig` property are standalone, not nested (`search`, `searchMaxSuggestions`). I agree that it would be better to have them all nested under a `searchOptions` property, but doing it right now would be inconsistent and confusing for users. Thus, I'd recommend naming your option `searchPlaceholder`, right under `themeConfig`.
- The PR currently only adds a placeholder to the built-in search, not the Algolia one. Maybe you could add the parameter for it as well.

What do you think?

**Comment by chris-visser** [comment]
@sarahdayan Thanks! Will do that somewhere between now and friday

**Comment by f3ltron** [comment]
i assigned you @sarahdayan as you answered if you ok with that to valid this pr

**Comment by kefranabg** [comment]
Hi @chris-visser,

Thanks for the PR. Do you still plan to work on it?

**Comment by chris-visser** [comment]
@kefranabg yup. Sorry that it takes so long. Haven't had time yet. I will try to push it this weekend

**Comment by kefranabg** [comment]
@chris-visser no problem 😉

**Pull request closed without merging**
