### PR TITLE
fix($shared-utils): improve title inference and header extraction for markdown links syntax

### PR DESCRIPTION
**Pull request by nuochong**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**before**
image

**after**
image

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [x] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by billyyyyy3320** [comment]
Please at least provide summary or the issue you were facing

**Comment by nuochong** [comment]
The following title cannot be resolved properly
```md
### [Subscript](https://github.com/markdown-it/markdown-it-sub) / [Superscript](https://github.com/markdown-it/markdown-it-sup)
### [\<ins>](https://github.com/markdown-it/markdown-it-ins)
### [\<mark>](https://github.com/markdown-it/markdown-it-mark)
```
It was wrongly parsed as
```html
<span>Subscript](https://github.com/markdown-it/markdown-it-sub) / [Superscript</span>
<span>\</span>
<span>\</span>
```
The correct analysis should be

```html
<span>Subscript / Superscript</span>
<span><ins></span>
<span><mark></span>
```
Sample snippet from: https://markdown-it.github.io/

**Review by billyyyyy3320 — COMMENTED** [review]
Thanks @nuochong! 

There're unit tests for both files, could you update test cases?

**Comment by nuochong** [comment]
sure

**Review by billyyyyy3320 — APPROVED** [review]

**Pull request merged**
