### PR TITLE
feat: support toml config

### PR DESCRIPTION
**Pull request by lbenie**
[#140]

### CODE REVIEW

**Comment by jaylinski** [comment]
What's the use-case for this, or: what's so bad about a js config?

Supporting all kinds of formats for a config file sounds like feature creep for me... (same for #115)

**Comment by yyx990803** [comment]
I think it's just users coming from other static site generators prefer some of these more popular formats. I think we'll support js, yaml and toml and that's it.

**Comment by yyx990803** [comment]
@lbenie I can verify the code is working with the preview - ccould you please delete the toml version of the config before I merge?

**Comment by lbenie** [comment]
@yyx990803 sure thing

**Pull request merged**
