### PR TITLE
Added hawkeye vulnerablity scanner and fixed major vulnerabilities

### PR DESCRIPTION
**Pull request by anusreePrakash**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- Added hawkeye vulnerability scanner and fixed some vulnerabilities

**Does this PR introduce a breaking change?** 
- [ ] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by kefranabg** [comment]
Hi @anusreePrakash, can you provide more context to this PR? What package vulnerabilities did you fixed? How did you proceed? Why would we need `hawkeye` dependency?

**Comment by anusreePrakash** [comment]
Hi @kefranabg, 
I just did an npm audit and found out that there are some latest versions of plugins available. so updated it in your repo.
The Hawkeye scanner-cli is project security, vulnerability and general risk highlighting tool.
It helps you to find the vulnerabilities and will prioritize for you. 
You can add it in your pipelines too and you can immediately get notified if got outdated

**Comment by kefranabg** [comment]
@anusreePrakash Could you use yarn instead of npm? Also we don't need to include hawkeye dependency if it's not something that is running in the CI.

**Comment by kefranabg** [comment]
Hey @Akryum it seems that vue-bot is not closing issue/PR after the 20 days. Any idea?

**Pull request closed without merging**
