### PR TITLE
feat: add suggestions num config

### PR DESCRIPTION
**Pull request by sakihet**
i'd like to customize suggestions num.
what do you think?

config example:
```
module.exports = {
  themeConfig: {
    searchBox: {
      suggestionsMax: 10
    }
  }
}
```

### CODE REVIEW

**Comment by wangyi7099** [comment]
Nice improvement

**Comment by sakihet** [comment]
@wangyi7099 thanks

**Comment by sakihet** [comment]
@cajames sure, i updated PR. please review again.

**Comment by yyx990803** [comment]
I simplified it a little bit to use `themeConfig.searchMaxSuggestions` instead.

**Pull request merged**
