### PR TITLE
feat($theme-default): refine sidebar groups

### PR DESCRIPTION
**Pull request by ulivz**
**Summary**

This PR contains following features:

1. `sidebarDepth` for a specified sidebar group;

  ```js
  module.exports = {
    themeConfig: {
      sidebarDepth: 1, /* Default sidebar depth */
      sidebar: [
        {
          title: 'foo',
          sidebarDepth: 2,  /* Override default sidebar depth for current sidebar */
          children: [
            ['', 'README'],
            'a',
            'b',
            'c',
            'd'
          ]
        }
      ]
    }
  }
  ```

   e.g. 

   - Change:

image

   - Before | After

  

2. Nested sidebar groups;

  ```js
  module.exports = {
    themeConfig: {
      sidebar: [
        {
          title: 'foo',
          children: [
            ['', 'README'],
            'a',
            'b',
            {
              title: 'foo/child',
              children: [
                'c',
                'd'
              ]
            }
          ]
        }
      ]
    }
  }
  ```

3. Clickable heading for sidebar groups.

  ```js
  module.exports = {
    themeConfig: {
      sidebar: [
        {
          title: 'foo',
          path: '/foo/', /* Sidebar of current heading will be clickable like a route link */
          children: [
            ['', 'README'],
            'a',
            'b',
          ]
        }
      ]
    }
  }
  ```

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [x] Related documents have been updated
- [x] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by ulivz** [comment]
cc @zyy7259

**Comment by davestewart** [comment]
Great! Much clearer than #669

**Comment by sirien-neiris** [comment]
Hi. Question, if I may.

It seems that this only allows creating "higher order" collapsing items in the menu (= there are source files, every source file is its own collapsible item in the menu, this allows to create one higher order collapsible item under which will cover this "standard level" items)

Is there a way how to make LOWER items in the menu collapsible? (= to make every lower-level heading inside source files collapsible as well)

We would really need this option, but it seems Vuejs currently doesn't allow that :(

**Comment by lunaceee** [comment]
Can I ask how the folder structure looks like for this?
```
module.exports = {
  themeConfig: {
    sidebar: [
      {
        title: 'foo',
        children: [
          ['', 'README'],
          'a',
          'b',
          {
            title: 'foo/child',
            children: [
              'c',
              'd'
            ]
          }
        ]
      }
    ]
  }
}
```

What i'm trying to achieve:
```
Topic Group 1
- Page 1A
    - Sub-page 1A-a
    - Sub-page 1A-b
- Page 1B
- Page 1C
    - Subpage 1C-a

Topic Group 2
- Page 2A
- Page 2B
    - Sub-page 2B-a
    - Sub-page 2B-b
- Page 2C
```

Thanks!

**Pull request merged**
