### PR TITLE
refactor($theme-default): extract page components

### PR DESCRIPTION
**Pull request by mathieutu**
**Summary**
Hi,
This PR extract the Edit and Nav components from default theme Page component.
It allows us to replace easily theses components when extending the template, by replacing only the targeted component and not the whole page.

There is no any change visually speaking.

Thanks for your work!
Matt'

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [x] Code style update
- [x] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

### CODE REVIEW

**Comment by ulivz** [comment]
//cc @Shigma

**Comment by mathieutu** [comment]
(I think the more we'll split templates in small components the more it'll be easy to use and overwrite them.)

**Comment by mathieutu** [comment]
Maybe could we merge it, then?

**Comment by f3ltron** [comment]
I know it's been a while since you create the pr @mathieutu i will have a look soon. It look great can you just please resolve the conflict please ?

We will need to update the doc part too about it

**Comment by f3ltron** [comment]
Before approve it i have to check the theme override on it if it's working or not but it look good

**Pull request merged**
