### PR TITLE
fix: add missing hash in #1706

### PR DESCRIPTION
**Pull request by kidonng**
**Summary**

Add missing hash in #1706.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by f3ltron** [comment]
the hash could be undefined ?

**Comment by kidonng** [comment]
Never.
```js
new URL('https://www.google.com/').hash === '' // true
```

**Comment by kidonng** [comment]
Oops then this should close #1775

**Comment by f3ltron** [comment]
Ok cool i will have a look and see with other to validate the PR. Thank's for your time

**Pull request merged**
