### PR TITLE
fix($core): render static html via stream pipe (fix #1819)

### LINKED ISSUE #1819: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
- [ x] I confirm that this is an issue rather than a question.

#### What is expected?
Normal build

#### What is actually happening?
```
sh deploy.sh
$ npx --max_old_space_size=8192 vuepress build docs
wait Extracting site metadata...

.....

Language does not exist tip
wait Rendering static HTML...
Rendering page: /elasticsearch-senior/depth-search/11-dis-max-best-fields.html
<--- Last few GCs --->

[8980:000002394C5333A0]   373053 ms: Mark-sweep 1368.8 (1442.2) -> 1368.8 (1442.2) MB, 1347.0 / 0.0 ms  allocation failure GC in old sp
ace requested
[8980:000002394C5333A0]   374704 ms: Mark-sweep 1368.8 (1442.2) -> 1368.8 (1427.2) MB, 1574.2 / 0.0 ms  last resort GC in old space req
uested
[8980:000002394C5333A0]   376188 ms: Mark-sweep 1368.8 (1427.2) -> 1368.8 (1427.2) MB, 1484.7 / 0.0 ms  last resort GC in old space req
uested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000019575F25879 <JSObject>
    2: exec(this=000000FD275E10B1 <JSRegExp <String[40]: ^\/cache-pdp\/dr\/131\.html(?:\/(?=$))?$>>,0000026741B33FA9 <String[62]: /elas
ticsearch-senior/depth-search/11-dis-max-best-fields.html>)
    3: 0000008D3FABD9D1 <Symbol: Symbol.match>(aka [Symbol.match])(this=000000FD275E10B1 <JSRegExp <String[40]: ^\/cache-pdp\/dr\/131\.
html(?:\/(?=$))?$>>,0000026741B33FA9 <String[62]: /elasticsearch-s...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewCodeRaw
 5: v8::internal::Factory::NewCode
 6: v8::internal::compiler::Linkage::GetSimplifiedCDescriptor
 7: v8::internal::RegExpImpl::Exec
 8: v8::internal::RegExpImpl::Exec
 9: v8::internal::RegExpImpl::Exec
10: v8::internal::RegExpImpl::Exec
11: v8::internal::RegExpImpl::Exec
12: v8::internal::RegExpImpl::Exec
13: v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
14: 0000029C5CD843C1
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

#### Other relevant information
An error occurred while building the repository：https://github.com/zq99299/note-book

### PR DESCRIPTION
**Pull request by sgtcoolguy**
**Summary**
This PR attempts to handle larger doc sites to avoid blowing up the NodeJs heap as seen in #1819, as well as provide a better experience by not just silently chewing through thousands of files. The PR attempts to achieve this by:
- Using [p-limit](p-limit) to limit the number of static HTML pages it attempts to render simultaneously. I arbitrarily chose 50.
- Using `bundleRenderer.renderToStream()` and then using `fs.writeStream()` and `stream.pipe()`. This avoids rendering to a string that we then write to file. It *should* pipe it to the file as it goes (which I assume should reduce RAM usage)
- Providing a nice progress bar that looks/feels slightly similar to the Webpack client./server ones earlier in the process.

Screen Shot 2020-06-19 at 10 05 55 AM

I should note that for our site with 1618 pages, I still had to increase the Node heap or it would sometimes blow up during the Webpack client/server bundling.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [X] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

While this adds an explicit dependency on p-limit, I did find it in the `node_modules` tree of my site, and I believe it was already deeply nested in the dependency chain of VuePress: `@vuepress/core > copy-webpack-plugin > p-limit` I aligned versions so it used `^2.2.0`.

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
cc @f3ltron I think from the linked issue, you may be the most relevant reviewer for this PR?

**Comment by sgtcoolguy** [comment]
I'm going to close this PR. After using it for some time it has a significant performance degradation. Also, we worked around our underlying issue in that we moved off using Travis to build (it was killing the build because of no output for 10+ minutes)

**Comment by 8zf** [comment]
@sgtcoolguy , hello, I've just read about this, and I'm experiencing this js oom issue recently. Since this pr is closed, is there any other wok around on this?

**Comment by sgtcoolguy** [comment]
@8zf basically I just had to "throw RAM" at Node: `NODE_OPTIONS="--max-old-space-size=6144" vuepress build docs`
Tweak that value to give it more RAM to work with. I have older CI nodes with only 8Gb RAM, so I had to get it to 6Gb like this - but if you have newer machines with more RAM you could crank that up.

**Comment by 8zf** [comment]
I've tried this, but in my case, there are 700+ pages(auto generated), which costs all 8gb ram I allocated and still OOM....
On the server machine(we got a service to generate and build pages on cloud), the situation could be better, I can allocate more ram, but I think that's not a solution in the long term😨.
So I have to add extra code to automatically replace the build/index.js file to build pages one by one.

I think this PR is a good way to solve problem like this, maybe you can add some configuration to vuepress to trigger build page by sequence/batch, or when large number of pages are detected :)

**Comment by sgtcoolguy** [comment]
I opened this PR to try and solve the issue - but:
- I still saw occasional OOM with webpack if I didn't crank up the RAM
- It was *way* slower
- I'm not a VuePress dev and don't really plan on continuing with the patch since it didn't even solve my own need and no one on the dev team commented or picked up the patch

So hey - you can fork and try the patch as a starting point, go right ahead - but I think it ultimately didn't solve the problem and instead introduced a huge performance regression. A simpler patch may work better for you just using something like p-limit to throttle the number of simultaneous renders.

**Comment by 8zf** [comment]
Maybe the dev team is too busy to handle so many problems. 😅

Really appreciate your advice :), I'll have a try

**Pull request closed without merging**
