### PR TITLE
Update build.js

### PR DESCRIPTION
**Pull request by BoltDoggy**
fixed:

> Run `vuepress build` success, then will be not exit at some version of node.

**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot: 

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by ulivz** [comment]
Thanks for the contribution.

> ... then will be not exit at some version of node.

Could you be more specific? which version?

**Comment by BoltDoggy** [comment]
@ulivz 
```
# system
ProductName:    Mac OS X
ProductVersion: 10.13.5
BuildVersion:   17F77
# node
v10.3.0
#npm
6.1.0
```

before fixed

```
# time && npm run build && time
shell  1.34s user 0.54s system 0% cpu 4:41.59 total
children  32.25s user 6.19s system 13% cpu 4:41.59 total

> blog-vuepress@1.0.0 build ...
> vuepress build src

Extracting site metadata...

Rendering static HTML...

Success! Generated static files in src/.vuepress/dist.
shell  1.34s user 0.54s system 0% cpu 5:44.49 total
children  48.50s user 7.76s system 16% cpu 5:44.49 total
```

after fixed

```
# time && npm run build && time
shell  1.31s user 0.53s system 0% cpu 3:51.14 total
children  18.04s user 4.78s system 9% cpu 3:51.14 total

> blog-vuepress@1.0.0 build ...
> vuepress build src

Extracting site metadata...

Rendering static HTML...

Success! Generated static files in src/.vuepress/dist.
shell  1.31s user 0.53s system 0% cpu 4:03.08 total
children  32.24s user 6.17s system 15% cpu 4:03.08 total
```

Alse node v8.9.4.

**Comment by BoltDoggy** [comment]
Sorry report

before fixed

```
# time npm run build
npm run build  16.15s user 1.56s system 27% cpu 1:03.66 total
```

after fixed

```
npm run build  14.16s user 1.38s system 130% cpu 11.927 total
```

**Comment by ulivz** [comment]
Thanks but I cannot reproduce it, so could you provide a convincing reason or the root of this "issue" to add this line? 

**FYI**: explicitly calling `process.exit` is a [bad practice](https://www.nczonline.net/blog/2014/02/04/maintainable-node-js-javascript-avoid-process-exit/):

**Comment by ulivz** [comment]
Closing it because of https://github.com/vuejs/vuepress/commit/fa473a7262627d5d9515baab2deeddd184cf2520

**Pull request closed without merging**
