### PR TITLE
[+] Support to load WebP images

### PR DESCRIPTION
**Pull request by boboidream**
**Summary**
Update webpack config, support to load WebP images.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [x] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by f3ltron** [comment]
@sarahdayan It look good to me.

**Comment by f3ltron** [comment]
@frankdugan3 I am not sure if it's usefull but as it's not something that will break the app i am ok with that

**Comment by kefranabg** [comment]
@boboidream why would you need this? I already tried to add `webp` image in vuepress and it's already working.

**Comment by boboidream** [comment]
> @boboidream why would you need this? I tried to add `webp` images in vuepress and it's already working.

@kefranabg thanks.

Add this to avoid compiling errors when using a webp images in markdown files.`docs/ file.md`
```
![image](./img/dui.webp)
```
errors

Everyone who wants to solve this errors needs to configure the `.vuepress/config.js`
```js
  chainWebpack: (config, isServer) => {
    const inlineLimit = 10000
    config.module.rule('images')
      .test(/\.(png|jpe?g|gif|webp)(\?.*)?$/)
      .use('url-loader')
        .loader('url-loader')
        .options({
          limit: inlineLimit,
          name: `assets/img/[name].[hash:8].[ext]`
        })
  }
```

So, I think adding configuration of  vueprese is a better way.

**Comment by boboidream** [comment]
This issue is't solved in vuepress@1.1.0.


Screen Shot 2019-10-05 at 12 57 08 PM

**Comment by kefranabg** [comment]
@boboidream check this [gitpod example](https://c2fc6787-f27b-47e1-92d7-9e905bb40a73.ws-eu0.gitpod.io/#/workspace/vuepress) I added a `webp` image on the vuepress homepage

**Comment by nicolas-t** [comment]
Hello, I'm getting this error too : https://github.com/vuejs/vuepress/pull/1833#issuecomment-538616805

@kefranabg The gitpod link you shared seems broken, can you share your example somewhere else ?

Thanks

**Pull request closed without merging**
