### PR TITLE
fix($theme-default): close dropdown on mouseout (fix #2227)

### LINKED ISSUE #2227: Overlap on a Navbar Dropdown
- [x] I confirm that this is an issue rather than a question.

## Bug report

When one clicks on several options in the navbar, their drop-down menu options overlap.

#### Steps to reproduce

IMG
Screenshot 2020-03-17 at 12 12 23 PM

If you are reporting a bug that can ONLY be reproduced on your repository, PLEASE provide this repo link. That takes guessing work out of the way and saves us time. 

This can be reproduced on any vuepress site with navbar items included.

#### What is expected?
I should be able to configure the navbar in such a way that this overlap is avoided. It sometimes takes a few secs to get out of this situation when it occurs. Also helpful if there's a way to disable focus on the parent navbar item.

#### What is actually happening?
When I click on several navbar items with dropdown I get this behavior where all dropdown overlaps.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
```bash
Environment Info:

  System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 13.9.0 - ~/.nvm/versions/node/v13.9.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.9.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 73.0.1
    Safari: 12.1.1
  npmPackages:
    @vuepress/core:  1.2.0
    @vuepress/theme-default:  1.2.0
    vuepress: ^1.2.0 => 1.2.0
  npmGlobalPackages:
    vuepress: Not Found
```

### PR DESCRIPTION
**Pull request by Mister-Hope**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge
- [ ] IE

### CODE REVIEW

**Comment by acgotaku** [comment]
The PR cause you can not open `Languages` dropdown in mobile mode. Please check at vuepress.vuejs.org .Thank you!

**Comment by Mister-Hope** [comment]
> The PR cause you can not open `Languages` dropdown in mobile mode. Please check at https://vuepress.vuejs.org/ .Thank you!

Reproduced on my dad's iPhone, sorry for that, I don't have an iPhone iPad or Mac, it seems that safari has it's different way to deal with `pointer-events`, not the same as recommanded. I will try to fix it at once.

**Comment by Mister-Hope** [comment]
I searched some forum and docs, and since safari has it's own behavior, it will be unpossible to solve this problem with css.

I will fix it by adding some functions to solve this problem.

**Comment by newsbielt703** [comment]
@acgotaku Oops, nice Catch.

**Comment by acgotaku** [comment]
@newsbielt703 @Mister-Hope  Thanks for your reply!

**Comment by Mister-Hope** [comment]
I fix this issue on PR #2339 , you can try it out. @acgotaku  @newsbielt703 .

**Pull request merged**
