### PR TITLE
feat: back to top

### PR DESCRIPTION
**Pull request by ycmjason**
Implemented https://github.com/vuejs/vuepress/issues/372

Well the icon looks a little bit funny, would be nice if some one could provide a better icon.

image

cc @ulivz @meteorlxy

### CODE REVIEW

**Comment by hmatalonga** [comment]
Can I suggest, for example, checking out the great Steve Schoger icon sets like [this one](http://www.zondicons.com/icons.html). They are free and in svg format for any styling needs :smile:

**Comment by ulivz** [comment]
Can we leverage more vue-styled back-to-top ? 😅

**Comment by ycmjason** [comment]
@ulivz do you mean the actual appearance? Or is it the coding style? I edited the code a little bit which I think is nicer, tell me what you think 😄

**Comment by meteorlxy** [comment]
@ycmjason I think @ulivz means ... the css style 🤣

**Comment by ycmjason** [comment]
@meteorlxy @ulivz 
If about css style, then I guess the style is definitely not finalised. I am waiting for an image input.

**Comment by leovafme** [comment]
How about something like that?
example back top

preview: https://codepen.io/anon/pen/OZZZYa

**Comment by meteorlxy** [comment]
@leovafme I like this.

- Add `translateY(5px)` to the arrow would be better. https://codepen.io/meteorlxy/pen/oddJdZ
- Don't forget `$accentColor` on `:hover`~

**Comment by ycmjason** [comment]
@leovafme @meteorlxy 
How about removing the frame?

**Comment by ycmjason** [comment]
@leovafme @meteorlxy 
Thanks for the suggestions! Using your inspirations, I created something similar and I think it integrate with the current theme quite nicely.

image

**Comment by meteorlxy** [comment]
@ycmjason 

Cool! I would vote this one as the final design 🎉

**Comment by ycmjason** [comment]
@meteorlxy YEAHH!! I am such an artist! HAHA

**Comment by meteorlxy** [comment]
Still need some tweaks~

**Comment by ycmjason** [comment]
@meteorlxy should the arrow be in `$borderColor` instead of `$textColor`? Would it be better? Well I guess we need input from @ulivz

**Comment by leovafme** [comment]
@ycmjason @meteorlxy, and what if you use the variable $accentColor? maybe it would go well with the color theme
what do they say?

**Comment by o15a3d4l11s2** [comment]
I have added a sample inside the related task: https://github.com/vuejs/vuepress/issues/372#issuecomment-392249334

**Comment by ycmjason** [comment]
@o15a3d4l11s2 thanks.

I guess I will just wait for the input from @ulivz before changing anything.

**Comment by ulivz** [comment]
This design looks good to me, Thanks! 

@o15a3d4l11s2 @ycmjason could you both work together to complete it?

**Comment by ycmjason** [comment]
@o15a3d4l11s2 can you please provide the image for the arrow? SVG or PNG? So that I could add it? Also should we use the green one or the upside down Vue one? I prefer the green one personally, but we can try both.

**Comment by o15a3d4l11s2** [comment]
@ycmjason You can find the svg attached. [VuePress_ToTop.zip](https://github.com/vuejs/vuepress/files/2052968/VuePress_ToTop.zip)

**Comment by ycmjason** [comment]
@o15a3d4l11s2 alright! I will put in that icon before this weekend.

**Comment by ycmjason** [comment]
Should I keep the "hover to green" feature?

**Comment by ycmjason** [comment]
image

Not on hover
image


On hover:
image

**Comment by ycmjason** [comment]
Well, just my personal preference. I think the previous arrow looks a bit better 🤣

**Comment by o15a3d4l11s2** [comment]
@ycmjason , I agree, my icon looks too sharp compared to the whole design.

**Comment by o15a3d4l11s2** [comment]
In case you do not like something (corner radius, length, etc.) feel free to drop me a line and I will immediately update it.
[chevron-up.zip](https://github.com/vuejs/vuepress/files/2108109/chevron-up.zip)

**Comment by ycmjason** [comment]
@o15a3d4l11s2 sorry for procrastinating too much. I have just picked this up.

**Comment by ycmjason** [comment]
@o15a3d4l11s2 I think the new icon looks pretty cool!

**Comment by m5o** [comment]
https://icons8.com/icon/pack/arrows/all Is my primary icon source. Use it for inspiration 

If its just the arrow, why not use pure css?
https://www.w3schools.com/howto/howto_css_arrows.asp

**Comment by ulivz** [comment]
@ycmjason Thanks for the great work, now I make it as a plugin [here](https://github.com/vuejs/vuepress/tree/next/packages/%40vuepress/plugin-back-to-top).

**Comment by meteorlxy** [comment]
@ycmjason welcome back jason 😃 

My slack account on vuepress workspace is deactivated and I could not access it... 😅

**Comment by ycmjason** [comment]
@meteorlxy

Ya my account is deactivated as well. I wanted to find you but I couldn't. Should we open another channel to communicate?

**Pull request closed without merging**
