### PR TITLE
feat(client render): merge options after enhance app fix #1631

### LINKED ISSUE #1631: enhanceApp options should merge options we pass
## Feature request

actually i am building additional page from components with docs

https://github.com/f3ltron/vuepress-plugin-docgen

```jsx

// https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/core/lib/client/app.js#L88

const options = {}

  try {
    appEnhancers.forEach(enhancer => {
      if (typeof enhancer === 'function') {
        enhancer({ Vue, options, router, siteData, isServer })
      }
    })
  } catch (e) {
    console.error(e)
  }

  const app = new Vue(
    Object.assign(options, {
      router,
      render (h) {
        return h('div', { attrs: { id: 'app' }}, [
          h('router-view', { ref: 'layout' }),
          h('div', { class: 'global-ui' }, globalUIComponents.map(component => h(component)))
        ])
      }
    })
  )

```
#### What problem does this feature solve?

when we use some front plugin like vue18n in my case by letting me merge my options into options there will be no more bug for $t is not define

#### What does the proposed API look like?

The merge should merge dynamically our options

#### Are you willing to work on this yourself?

i can if it's accepted

### PR DESCRIPTION
**Pull request by f3ltron**
by merging options we open door for injections into front more easier like in my cas vue18n that i
needed because i added via additonnal page component with a preview

fix #1631 

**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [x] Related tests have been updated not needed

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by f3ltron** [comment]
it can let the door to add some client store that actually is not possible

**Comment by f3ltron** [comment]
I think actually the options was made for that.

But it will be all time empty actually that's why i added that

**Comment by f3ltron** [comment]
is it relevant or not :) ?

**Comment by MickaMx** [comment]
Hi @ulivz, any idea of when this will be merged?

**Comment by f3ltron** [comment]
@MickaMx I know that's me who create the issue but i don't have a lot of time right now...

Can just explain here your use case that i will create a documentation to that

**Comment by kefranabg** [comment]
I think documentation should be updated right?

**Comment by meteorlxy** [comment]
:thinking: see https://github.com/vuejs/vuepress/issues/1631#issuecomment-533820410

**Comment by ulivz** [comment]
Same question with @meteorlxy 😅

**Comment by f3ltron** [comment]
It's look it change the option by reference that is not a good way to do.

It's not just a pure function and can be source of bugs

**Comment by meteorlxy** [comment]
Closing this for housekeeping

**Pull request closed without merging**
