### PR TITLE
feat($cli): Notify users of a newer release

### LINKED ISSUE #2119: [CLI]: 🔔Notify users if they're using an older version
#### What problem does this feature solve?
Users are notified about a newer release and they no longer have to stay on an outdated version.

#### How should this be implemented in your opinion?
[update-notifier](https://www.npmjs.com/package/update-notifier) serves the purpose here. As from the tagline, `Inform users of your package of updates in a non-intrusive way`.

#### Are you willing to work on this yourself?
Yeah ofc :+1:

### PR DESCRIPTION
**Pull request by jamesgeorge007**
**Summary**
Notify users of an newer release so that they don't end up in an outdated version. 
Closes #2119 

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by meteorlxy** [comment]
The lockfile is not updated

**Comment by meteorlxy** [comment]
The lockfile is not updated @kefranabg @newsbielt703

**Comment by meteorlxy** [comment]
I've updated it in 5d6adf1f2555180104f305390bfced433aeab279

**Comment by newsbielt703** [comment]
Thanks. I should have noticed.

**Comment by kefranabg** [comment]
Nice catch @meteorlxy thanks

**Pull request merged**
