### PR TITLE
feat: code line number (close: #365)

### PR DESCRIPTION
**Pull request by ulivz**
cc @egoist , it also fixed a empty line highlight issue:

```js
`<span class="highlighted-line">${split || '\n'}</span>`
```

# Snapshot

## Highlight line + Line number

image

## Only line number

image

## Only Highlight line

image

### CODE REVIEW

**Comment by ycmjason** [comment]
I think it would be nicer to make this a separate markdown-it plugin. Semantically it is not right to put this feature in highlightLines plugin.

P.S. I am working on the same thing too but haven't yet complete it.

**Comment by ycmjason** [comment]
Also, the current implementation make the line number selectable? Which might not be ideal?

**Comment by ulivz** [comment]
> 1. make this a separate markdown-it plugin

Sure, I originally make it as a separate plugin, but since `markdown-it-highlight-lines` rewrite the render method, so it won't work.

> 2. the current implementation make the line number selectable

have handled for that.

**Comment by xkcoding** [comment]
@ulivz Unbelievable. That's what I want.

**Comment by ulivz** [comment]
# Updated 5-13

## Desktop

line-numbers

## Mobile
line-numbers-mobile

**Pull request merged**
