### PR TITLE
docs: improve getting started guide

### PR DESCRIPTION
**Pull request by adriatic**
The proposed addition to the Quick Step method builds the generated site - an action that is equivalent to "Step 3. Install VuePress locally" in the [Manual Installation](https://vuepress.vuejs.org/guide/getting-started.html#manual-installation) variant.

**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by waldyrious** [comment]
I was going to suggest precisely this change! However, I would suggest reusing the same wording in the README of [create-vuepress-site](https://github.com/vuepress/create-vuepress-site), which is clearer and more explicit. In particular, instead of the sentence added in this PR (which is more appropriate as a description of this PR rather than as instructions to the user):

> In order to make the [Quick Start](https://vuepress.vuejs.org/guide/getting-started.html#quick-start) and [Manual Installation](https://vuepress.vuejs.org/guide/getting-started.html#manual-installation)  functionally equivalent, the Quick Start method needs one more step:

I'd suggest simply replacing the existing line

> Once it is complete, you should see your new VuePress site scaffolded in your directory! :tada: 

...with the last sentence of the "Run generator" section in create-vuepress-site's README, as that is clearer about what will have just happened, including the mention of the `docs` directory:

> This will create a scaffolded documentation site in the `docs` directory that is enclosed from the rest of the folder.

Then, I'd add the contents of the "Setup local environment" (all three commands, not just the `npm install` one).

WDYT @adriatic?

**Comment by adriatic** [comment]
@waldyrious Happy to see that I am not the only one that spotted this relatively minute detail in the [README.md](https://github.com/vuepress/create-vuepress-site#create-vuepress-site) document. However, since that README.md file is not the same as it was at the time I proposed my suggestion for its improvement, I cannot comment on your proposed change. Please see to get this finished correctly, nevertheless - and thank you

**Comment by waldyrious** [comment]
@adriatic if you add me as a collaborator in your fork, I'd be happy to update the PR and follow up with the maintainers to get it merged :)

**Comment by adriatic** [comment]
@waldyrious - one could not ask for a better favor. Much appreciated (your invite to https://github.com/adriatic/vuepress is pending.

**Comment by waldyrious** [comment]
> your invite to adriatic/vuepress is pending.

Thank you! Just accepted it. I'll try to update the PR this weekend.

**Comment by waldyrious** [comment]
Hey @adriatic, I've made the edits I mentioned above and a few others for additional clarity. Can you take a look and let me know what you think?

**Comment by waldyrious** [comment]
Hey @meteorlxy — if it's not too much trouble, please take a look and let us know if these changes are acceptable. Happy to make any adjustments you may deem necessary.

**Comment by adriatic** [comment]
@waldyrious Well, I am not able to follow your PR with the details you deserve. The process of creating a PR and pushing into a branch has changed sufficiently to confuse me. It is defined as a workflow using GitHub actions

image

I would have to learn this so, let's not wait until then, since we were on the identical "page" before you started this. Thanks for doing it the proper way.

**Comment by waldyrious** [comment]
I wouldn't worry about the Checks tab :) the GitHub Actions workflows are not specifically related to this PR. They have been set up in this repository for all contributions. All I did was `git clone` your fork, `git checkout` this PR's branch (`patch-1`), edit the file, amend the commit and push the updated commit back to your fork. Anything else is automated setup that neither I nor you need to worry about.

There is one thing you need to do though, which is update the title of thus PR to match the [semantic commit guidelines](https://github.com/probot/semantic-pull-requests). Changing it to something like "docs: Improve getting started guide" should work. Just click on the "Edit" button to the right of the PR title to edit it.

**Comment by meteorlxy** [comment]
Thank you very much for your contribution, I'll try to find time to review this PR.

Not sure if you have notice this announcement https://github.com/vuejs/vuepress/issues/2744. It will be great if you could help to enhance our docs of vuepress v2

**Comment by waldyrious** [comment]
Hi @meteorlxy, just a friendly ping :)

**Comment by adriatic** [comment]
@waldyrious - changed the title as you suggested. This issue took its time 😄

**Review by meteorlxy — APPROVED** [review]
LGTM

**Pull request merged**
