### PR TITLE
workflow: simplify changelog

### PR DESCRIPTION
**Pull request by ulivz**
**Summary**

We don't need these `fixes` of `feat` commits which are irrelevant to actual code to appear in changelog, such as CI, documents, etc. because these do not take any effects to user's code.

IMO, these informations plus real changelog can be archived into a unified section, such as "release note"? This is worth discussing.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by f3ltron** [comment]
Ok i did a very technical changelog before only but yeah definitely agree here

**Comment by ulivz** [comment]
@kefranabg Please do not use `fix` for docs-related changes.

image

**Comment by kefranabg** [comment]
@ulivz what prefix do you recommand when the topic is about documentation updates?

**Comment by kefranabg** [comment]
Oops @ulivz I deleted your comment instead of mine 😅 Don't know how to revert it

**Pull request merged**
