### PR TITLE
fix: webpack absolute output path

### PR DESCRIPTION
**Pull request by ekoeryanto**
**Summary**

**What kind of change does this PR introduce?** (check at least one)
image

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [x] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot: 

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by ekoeryanto** [comment]
@ulivz, so we need appveyor here.
here the log from my forked vuepress
https://ci.appveyor.com/project/ekoeryanto/vuepress/build/job/w159tutdupa997nv

**Comment by mAKEkr** [comment]
@ulivz upath is problem on webpack path detection.
webpack/webpack#66

**Comment by ekoeryanto** [comment]
@ulivz I think this is an urgent issue for windows users.
I'm afraid we need to revert 19e73d7ea0ca71c1eb538b1eaf688165fe16308e for safety reason

**Comment by meteorlxy** [comment]
BTW, I suggest to use exact version requirement for alpha/beta releases, so we can revert to the exact version quickly.

i.e.
```js
  "dependencies": {
    "@vuepress/cli": "^1.0.0-alpha.5",  // ^1.0.0-alpha.5 => 1.0.0-alpha.5
    "@vuepress/core": "^1.0.0-alpha.5",  // ^1.0.0-alpha.5 => 1.0.0-alpha.5
    "@vuepress/theme-default": "^1.0.0-alpha.5"  // ^1.0.0-alpha.5 => 1.0.0-alpha.5
  },
```

**Comment by ekoeryanto** [comment]
It is fixed by d89f766be1649fa3388d51f0a76440ccfb85095e

but after I reread the source, I think the better place to fix the issue is [here](https://github.com/vuejs/vuepress/blob/8abd976aa7c207f18fe837fda42a158b55d57df7/packages/%40vuepress/core/lib/webpack/createBaseConfig.js#L39)

Sorry :smile:

**Pull request closed without merging**
