### PR TITLE
feat($core): config pattern of resolved files

### LINKED ISSUE #1700: Parametrize pattern of pages resolved
## Feature request

Right now the pattern configuration of what files should be resolved as pages is hardcoded in core module of vuepress (APP.js line 319). The intention it's to open the door to parametrizing this pattern configuration from the siteConfig.

#### What problem does this feature solve?

To remove folders of specific files matching some pattern from the final vuepress site. A common scenario is where you are documenting a project that has a bunch of vue files you don't want to expose as documentation. 

With this approach we could change this pattern:
`['**/*.md', '**/*.vue', '!.vuepress', '!node_modules']`

To have something like:
`['**/*.md', '!.vuepress', '!node_modules']`

Or like this:
`['**/*.md', '**/*.vue',  '!**/vue-folder/*.vue', '!.vuepress', '!node_modules']`

#### How should this be implemented in your opinion?

The proposal it's to add the logic in resolvePages method to retrieve the pattern from siteConfig, if not use the default one:

```
  async resolvePages () {
    // resolve pageFiles
    const patterns = this.siteConfig.patterns ? this.siteConfig.patterns : ['**/*.md', '**/*.vue']
    patterns.push('!.vuepress', '!node_modules');
```

So it can be easily configured from config.js:
```
module.exports = {
  title: 'Hello VuePress',
  description: '# Hello, VuePress!',
  dest: 'vuepress',
  base: 'vuepress',
  patterns: ['**/*.md', '**/*.vue', '!**/deploy.*'],
  head: [
    ['link', { rel: 'icon', href: '/logo.png' }]
  ]
}

```

#### Are you willing to work on this yourself?

Yes, it's a necessity we have in our current project and i would like to work on it.

### PR DESCRIPTION
**Pull request by eduardcotmrf**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x ] No

**The PR fulfills these requirements:**

Right now the pattern configuration of what files should be resolved as pages is hardcoded in core module of vuepress (APP.js line 319). The intention it's to open the door to parametrizing this pattern configuration from the siteConfig.

fix #1700 

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ x] Chrome
- [ x] Firefox
- [x ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ x] A convincing reason for adding this feature
- [ x] Related documents have been updated
- [ x] Related tests have been updated

### CODE REVIEW

**Comment by f3ltron** [comment]
Hello @eduardcotmrf Thank's for the catch ! Can you just add me a real example that it can be great. And it is perfect ! 👍

**Comment by f3ltron** [comment]
can you add into the zh doc too please even if it's in english

**Comment by eduardcotmrf** [comment]
Hey, i just came back from paternity leave, sorry for not answering for some time :)
Here i added the doc to zh as well in english.
Thanks!

**Comment by eduardcotmrf** [comment]
Can you merge it @f3ltron ?

**Pull request merged**
