### PR TITLE
feat: reenable search

### PR DESCRIPTION
**Pull request by s-pace**
cc #697

### CODE REVIEW

**Comment by f3ltron** [comment]
The doc actually working but i didnt know about algolia part. You just tried in local ? 

As long as i know algolia scrap the website to have informations and make the search working.

Is it up to date ?

@sarahdayan  I am sure you have informations ^^

**Comment by s-pace** [comment]
👋 @f3ltron 

The vuepress website is currently using the javascript search. This PR enables [the Docsearch search experience instead](https://community.algolia.com/docsearch/). It comes with some extra-feature such as typo tolerance. 

Your DocSearch index `vuepress` is up to date. Here is the output of your crawl:

image

**Comment by f3ltron** [comment]
I just didnt see you came from algolia ^^. Top i will just validate with others and will merge it soon.

Thank's @s-pace

**Comment by s-pace** [comment]
@f3ltron I will make it more clear next time. Thank you :)

**Comment by s-pace** [comment]
ETA when it will be deployed ?

**Comment by f3ltron** [comment]
i think next week @s-pace

**Comment by s-pace** [comment]
Thanks @f3ltron 🙏

**Pull request merged**
