### PR TITLE
feat($core): add canonical link to frontmatter

### PR DESCRIPTION
**Pull request by d-pollard**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

This feature introduces the ability to specify `canonical` in the frontmatter section on a page:

```
---
canonical: https://google.com
---
```

Which will then render the proper head HTML tag, and also keep it updated when the page changes

### CODE REVIEW

**Comment by d-pollard** [comment]
Partial resolution to https://github.com/vuejs/vuepress/issues/2153

**Comment by adamdehaven** [comment]
@d-pollard I can confirm (with your latest addition) that the `frontmatter.canonical` property works, and is also exposed to the `extendPageData` Options API, meaning it can be dynamically injected into the `frontmatter` :tada: 

This should **definitely** roll out ASAP - you're awesome!

**Comment by adamdehaven** [comment]
@d-pollard don't forget: the docs would need to be updated for this PR as well. 

Now you've got me thinking about injecting structured data in a similar way. It also would need to be updated on each route change. I wonder if I'm the only person that would like a hook in the Options API that would allow for injecting (via `extendPageData`) custom content/tags. In my use-case, I'd want to inject a `<script>` tag with JSON into the `<head>`, something like this:

``` js 
const structuredData = {
    '@context': 'https://schema.org/',
    '@type': 'WebSite',
    name: this.meta_data.title + (this.$page.frontmatter.subtitle ? ' | ' + this.$page.frontmatter.subtitle : '') || null,
    description: this.meta_data.description || null,
    url: frontmatter.canonical,
    image: {
        '@type': 'ImageObject',
        url: this.$site.themeConfig.domain + this.$site.themeConfig.defaultImage,
    },
    '@id': frontmatter.canonical,
}
```

``` html
<script type="application/ld+json">{{ JSON.stringify(structuredData, null, 4) }}</script>
```

I'm currently doing this with a custom component; however, it is technically rendered after the DOM, meaning it isn't available when the page is scraped (before JavaScript is enabled).

**Comment by d-pollard** [comment]
Yeah we could definitely look into a custom hook

Typically I write the feature in it's entirety then open another PR with docs code so that if the version changes, the feature code is still introduced and I can update the docs to reflect the proper version

**Comment by d-pollard** [comment]
Like in this case, I have reservations about using just the keyword canonical so with probably change it to be more idiomatic (thinking `canonicalLink` to reflect current codebase practices)

**Comment by adamdehaven** [comment]
@d-pollard I almost suggested a change regarding the `canonical` keyword. I post content on `dev.to` and they actually use the YAML keyword `canonical_url` instead, which, I think would be good; however, since other keywords are camelCase, maybe `canonicalUrl` instead? 

I lean towards `url` rather than `link` because `link` seems to reference more of the HTML `<link>` element itself, whereas url references the value, which is what the user would be providing in the `frontmatter`.

**Comment by d-pollard** [comment]
Yeah that makes sense, I'll make the changes probably tomorrow, and then document the feature once it's all merged in.


Doing this makes me wonder if I could also use the same pattern to introduce vue-meta in a way that's backwards compatible

**Comment by d-pollard** [comment]
I fibbed; I've updated the PR with the new terms; used `canonicalLink` for the SSR injection to reflect the HTML element it's injecting, and I've used `canonicalUrl` for the frontmatter value to reflect the actual use case

**Comment by adamdehaven** [comment]
That all looks good to me.

**Review by bencodezen — APPROVED** [review]
Thanks for the collab effort @d-pollard and @adamdehaven!

**Pull request merged**
