### PR TITLE
Update outbound link icon alignment

### PR DESCRIPTION
**Pull request by gtsiolis**
**Summary**

This will update outbound link icon alignment.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

| Before (header) | After (header) |
| ------ | ------ |
| image | image |

| Before (paragraph) | After (paragraph) |
| ------ | ------ |
| image | image |

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE

### CODE REVIEW

**Comment by gtsiolis** [comment]
@ulivz could you review or forward this?

**Comment by gtsiolis** [comment]
Thanks @ulivz! The goal was *not* to vertically align the icon but actually use `text-bottom` alignment in the first place. I think that both approaches are acceptable but let me know if you think this should vertically align the icon in the middle instead.

**Comment by Shigma** [comment]
> It's also centered when you change the font-size:

I think outbound link will look better if keeping the same size as fonts.

**Comment by ulivz** [comment]
@Shigma Yup but we can do it in another PR, since there are two things.

**Comment by Shigma** [comment]
> @Shigma Yup but we can do it in another PR, since there are two things.

I bet you are right.

**Comment by gtsiolis** [comment]
@ulivz I tried this out with a couple of different font sizes and the suggestion in https://github.com/vuejs/vuepress/pull/1308#pullrequestreview-204816792 looks much better for larger fonts. I've updated the code and the screenshots in the description. Let me know what you think.

**Comment by gtsiolis** [comment]
Thanks @ulivz! 😆

**Pull request merged**
