### PR TITLE
docs: update travis deploy

### PR DESCRIPTION
**Pull request by YunYouJun**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

`deploy`: deprecated key `skip_cleanup` (not supported in dpl v2, use cleanup)
> [Cleaning up the Git Working Directory](https://docs.travis-ci.com/user/deployment-v2#cleaning-up-the-git-working-directory)

`deploy`: key `github_token` is an alias for `token`, using `token`

### CODE REVIEW

**Comment by YunYouJun** [comment]
I use beta function so I get this tip.
In fact, the next major version dpl v2 which currently is in a preview release phase.
[The Travis CI Blog: Announcing dpl v2 developer preview release](https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release)

If you want to use `dpl v2`, you have to set

```yml
deploy:
    edge: true
```

Merge this PR later when it is officially released.

**Comment by kefranabg** [comment]
Hi @YunYouJun,

In the official documentation https://docs.travis-ci.com/user/deployment/pages/ `github_token` key is still used, and seems to be working as expected. Why would you want to change this?

**Comment by YunYouJun** [comment]
@kefranabg 
I find I used the travis beta function, so I get the alert about `github_token` and `skip_cleanup`.
But it has not officially released yet, so my PR may be too early.

**Comment by kefranabg** [comment]
@YunYouJun I think so 😛 I'll close the PR for now, feel free to submit a new one when it will be officially release

**Pull request closed without merging**
