### PR TITLE
feat(options): make enhancers async ready without breaking changes

### PR DESCRIPTION
**Pull request by Slashgear**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [ ] Related documents have been updated
**There is no dedicated documentation for async options for now**
- [x] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

I am working on a project where I use vuepress alpha.47. I am trying to fetch dynamically information for `$page` data base on a `frontmatter` value.

Here is the code of the plugin I am trying to introduce in my project.

```js
const { fetchUser } = require('./service');

module.exports = () => {
  const authors = {};

  return {
    name: "github",

    async extendPageData($page) {
      if($page.frontmatter.type === "post") {
        const githubProfile = $page.frontmatter.github_profile;

        if(!authors[githubProfile]){
          const fetched = await fetchUser(githubProfile); 
          authors[githubProfile] = fetched;

          $page.frontmatter.gh = fetched;
          return $page;
        }
      }
      return $page;
    }
  }
};
```

But extendPageData is not async ready for now.
So this is my contribution to make is async ready 🎉

Tested  locally with `yarn link`

### CODE REVIEW

**Comment by f3ltron** [comment]
Hello ! @Slashgear is it needed again ? You want to add the possibility to make async request on that that's the need behind ?

**Comment by Slashgear** [comment]
Yep, that was the need hidden behind.

It was needed for one of my project, but without answer I had to switch from static site generator. 
😞

**Comment by f3ltron** [comment]
sorry to hear that. as we create the core team we need a bit time to establish the needs and work on it.

**Comment by f3ltron** [comment]
Thank's for your work @Slashgear i have to look a bit about async stuff and test here but it look great !

**Comment by Slashgear** [comment]
@kefranabg I don't have the time now to do it :-)

So, go for it :smile:

**Pull request merged**
