### PR TITLE
test

### PR DESCRIPTION
**Pull request by delylaric**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by ulivz** [comment]
What problems does this PR solve?

**Comment by timaschew** [comment]
@ulivz Seriously?  
I've sent a PR 2 weeks ago: #1540 I haven't received any feedback yet but I was fixing the same issue with almost the same code. But this PR (with a ridiculous title) was merged. 

👎

**Comment by ulivz** [comment]
Merged? Are you blind?

**Comment by ulivz** [comment]
If you don't want to cooperate happily, please don't speak here.

**Comment by timaschew** [comment]
> Merged? Are you blind?

What are you talking about?  
My merge request (#1540) was neither merged nor I got any feedback for 2 weeks. But I was fixing same bug as this MR, which was submitted just 3 days ago.

> If you don't want to cooperate

It seems that you don’t want to cooperate.

**Comment by timaschew** [comment]
Oh, it was closed. Not merged. Got it, sorry ;)

**Pull request closed without merging**
