### PR TITLE
feat($core): redirects for clean urls

### PR DESCRIPTION
**Pull request by ulivz**
## Summary 

In VuePress, we have following convention about routing:

   - `/foo/` means source file is `/foo/{README|index}.md`
   - `/foo.html` means your source file is `/foo.md`

 The original design of VuePress relied on above two styles
 of routing, especially the calculation involved of routes at
// default theme. so we can't easily modify `/foo.html` directly
 to `/foo` (i.e. remove html suffix)

 This  utility handles redirect of clean urls, with this utility, you'll
 get:

 For unknown request `/foo`
   - redirect to `/foo.html` if it exists
   - redirect to `/foo/` if it exists

 For unknown request `/foo/`
   - redirect to `/foo.html` if it exists

If all the above redirect rules don't exist, you'll get a 404

---

**Note that** this PR doesn't provide you the ability to remove the
html suffix at the route level, it just allows you to use clean urls.

cc @octref 

---

Related: #603 
Related: #608
Related: #1060
Close: #720 
Close: #931

### CODE REVIEW

**Comment by awulkan** [comment]
If I understood this correctly, the routes will still end in .html? Or am I wrong?

**Comment by ulivz** [comment]
I have noted it in the description:

> **Note that** this PR doesn't provide you the ability to remove the
html suffix at the route level, it just allows you to use clean urls.

FYI, we don't plan to support removing the `html` suffix for now(1.x)

**Comment by awulkan** [comment]
> FYI, we don't plan to support removing the `html` suffix for now(1.x)

Oh, so that won't happen until 2.x? Which might not happen for a LONG time. I guess I'll use another static site generator for now then, because I can't afford losing search engine rankings when you eventually do allow non-.html links.

**Comment by ulivz** [comment]
It's up to you.

**Comment by Shigma** [comment]
@awulkan 

Now you can use [plugin-clean-urls](https://v1.vuepress.vuejs.org/plugin/official/plugin-clean-urls.html) if you want your urls to be `/foo/` or even `/foo` instead of `/foo.html`.

**Comment by nelson6e65** [comment]
OMG! Amazing, @Shigma

**Comment by awulkan** [comment]
@Shigma Well done. :)

**Pull request merged**
