### PR TITLE
fix($core): no dynamic import style

### PR DESCRIPTION
**Pull request by Shigma**
**Summary**

VuePress will create an empty chunk every time.

repro: https://github.com/Shigma/vuepress-generates-empty-chunk

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by timaschew** [comment]
What do you mean with empty chunk? I don't see empty chunks in https://github.com/Shigma/vuepress-generates-empty-chunk/tree/master/.vuepress/dist
Or do you expect to have an empty chunk with this change?

**Comment by Shigma** [comment]
@timaschew This is an empty chunk:

https://github.com/Shigma/vuepress-generates-empty-chunk/blob/c8e2bf746ac851aa87f191820e8c521590b7bb26/.vuepress/dist/assets/js/5.e8bcff97.js#L1

**Comment by Shigma** [comment]
@ulivz 

1. I have tested the overriding behavior by using the following test codes:

https://github.com/vuejs/vuepress/blob/a9739607ca0f962d9977b3d7c1d07d0f1d986cbf/packages/docs/docs/.vuepress/styles/index.styl#L3-L5
https://github.com/vuejs/vuepress/blob/a9739607ca0f962d9977b3d7c1d07d0f1d986cbf/packages/docs/docs/.vuepress/styles/palette.styl#L3

And it works as expected.

2. [Dynamic imports](https://webpack.js.org/guides/code-splitting/#dynamic-imports) is a part of code splitting.

**Comment by Shigma** [comment]
@ulivz Can you look into this PR one more time?

**Comment by f3ltron** [comment]
hello @Shigma i know it's been a while. But can you tell me more about your PR. What about the empty chunks stuff. 

I think about the generation of them. It's look great but i am not sure to understand

**Comment by Mister-Hope** [comment]
Can we have this pr merged? I think it is using the improt function which the webpack provides now, and he is changing it to es module syntax. So it will fix the empty chunk issue. @f3ltron

**Comment by Shigma** [comment]
@f3ltron 

`import()` will be interpretted as dynamic import, which means the file it imports should be emitted in a separate file.

**Comment by Mister-Hope** [comment]
@newsbielt703 @meteorlxy Could you check and merge this PR. Quite a long time since Shigma opened it.

**Comment by newsbielt703** [comment]
LGTM!  One more approval and it will be merged.

**Comment by Shigma** [comment]
Glad to see this merged. Thanks!

**Pull request merged**
