### PR TITLE
feat: option to disable svg in external links (close: #610)

### PR DESCRIPTION
**Pull request by ulivz**
**Summary**

- Close: #610 
- Release at: **0.11.0**

cc @octref 

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot: 

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [x] Related documents have been updated
- [x] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by octref** [comment]
I feel it might be better to put the option inside `externalLinks`, something like
```
externalLinks: {
  attributes: { target: '_blank', rel: 'noopener noreferrer' },
  symbol (or call it icon?): true | false
}
```

However, that is backward incompatible...However I feel it's better to have options organized and deprecate the original usage, now Vuepress is still pre 1.0.

**Comment by ulivz** [comment]
Agree with that, let's reorganize it. 

lol, I'm not very good at name, `icon` looks better to me.

**Comment by octref** [comment]
Sorry for all the opinions - but I feel this should actually be an option contributed from the theme with your plugin API. I think it would be great to start that early, so there can be clean separation between theme / core config.

**Comment by ulivz** [comment]
Actually, plugin API is almost done but I still have to spend some time optimizing it, and I also agree with that anything that can be done by plugin should be done by plugin.

But users are unable to modify the implementation of built in `makrdown-it` plugins through VuePress's plugin API. especially for `link`, as a core plug-in, we may not be able to separate it from core.

IMO, we can implement a low-level API at core for that, and each theme can determine its `public API / preset` by using plugin APIs.

**Comment by octref** [comment]
@ulivz Thanks - to keep the markdown clean, I think some common functionalities people expect from a MD renderer such as anchor and slug should be built-in, but also possible to turn off.
For everything cosmetic, they should go to the theme.

**Comment by destroytoday** [comment]
Hi! What's remaining with this PR in order to get it merged? (I'm eager to get it in since I just hit this issue myself when making a custom theme).

If the config var simply needs to change, I'd be happy to make a contribution to get everything wrapped up. Was something like the following the consensus? (to keep backwards-compatibility)

```
externalLinks: {
  target: '_blank',
  rel: 'noopener noreferrer',
  icon: true | false
}
```

(I'm not entirely sure if the most recent comments about using the plugin API were the final call, but for what it's worth, before finding the issue/PR, I expected to be able to set a boolean in the config)

**Comment by zlliang** [comment]
Also eager to get it!
For now I disable the icon through CSS:
```css
svg.icon.outbound {
  display: none;
}
```

**Comment by robmuh** [comment]
If you have ejected the default theme with 0.14.4 or so you can put the following in the `.vuepress/theme/styles/theme.style` file:

```stylus
.icon.outbound
  display none !important 
```

**Comment by ulivz** [comment]
In 1.x we can acquire it by removing the built-in markdown-it [link](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/markdown/lib/link.js) plugin and creating a custom link plugin:

```js
// .vuepress/config.js
module.exports = {
  chainMarkdown (config) {
    const { PLUGINS } = require('@vuepress/markdown')

    config
      .plugins
        .delete(PLUGINS.CONVERT_ROUTER_LINK)

    config
      .plugin(PLUGINS.CONVERT_ROUTER_LINK)
        .use(/* Your custom link plugin */)
  }
}
```

**Comment by adam-lynch** [comment]
For anyone else who needs it, this uses the same link plugin (so it works the exact same and supports the same options) except `<OutboundLInk/>` is removed from the result.

```js
// .vuepress/config.js
module.exports = {
  chainMarkdown(config) {
    const { PLUGINS } = require('@vuepress/markdown')
    const originalLinkPlugin = require('@vuepress/markdown/lib/link.js');

    config
      .plugins
        .delete(PLUGINS.CONVERT_ROUTER_LINK)

    const linkPlugin = function (md) {
      const result = originalLinkPlugin.apply(this, arguments);
      const close = md.renderer.rules.link_close;
      md.renderer.rules.link_close = function() {
        return close.apply(this, arguments).replace('<OutboundLink/>', '');
      }
      return result;
    };

    config
      .plugin(PLUGINS.CONVERT_ROUTER_LINK)
        .use(linkPlugin, [{
          // The config.markdown.externalLinks options https://vuepress.vuejs.org/config/#markdown-externallinks
          target: '_blank',
          rel: 'noopener noreferrer'
        }])
  },
};
```

**Comment by deancn** [comment]
@ulivz  is this update to docs? 
https://vuepress.vuejs.org/config/#markdown

**Comment by steveellis** [comment]
Removing the external link icon is tricky but doable with CSS. What caused me some pain was that the HTML generated from my build server was slightly different than the one locally, requiring different selection rules to excise it.

This is what can work when it is built locally.... It doesn't have the span, it's just an svg inside the external link (here selected with the target attribute). There's probably a more precise selector but whatever...

```
a[target] svg {
  display: none !important;
}
```

This is what it looks like when built with yarn in the development pipeline.
```
a[target] span { 
  display: none !important
} 
```
Just putting both those rules in theme.styl worked for me.

**Pull request closed without merging**
