### PR TITLE
fix: update copy-webpack-plugin @vuepress/core for security

### PR DESCRIPTION
**Pull request by mohawk2**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [x] Other, please describe: dep update to fix security vulnerability

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by rekmarks** [comment]
It would be great if this got merged in order to fix: https://www.npmjs.com/advisories/1548

**Comment by mohawk2** [comment]
82 open PRs. Nevertheless, I choose to live in hope :-D

**Comment by mohawk2** [comment]
@bencodezen Any chance of a review? Or, if you're not interested I can close. Happy to reduce the "cobwebs" of open PRs either way ;-)

**Comment by genygilles** [comment]
This PR would also fix a vulnerability in `ssri` https://github.com/advisories/GHSA-vx3p-948g-6vhq, from `webpack-copy-plugin/cacache`

**Comment by mohawk2** [comment]
I've updated this to resolve the conflict on `yarn.lock`. @billyyyyy3320 Given there are two different security vulnerabilities that would be fixed by this, any chance of a review/merge?

**Pull request closed without merging**
